reportReader:
  enabled: true
  name: frontend4e5a
  nodeSelector: 
    role: usernp1
  image: 
    repository: acr7c02.azurecr.io/frontend
    pullPolicy: IfNotPresent  
    tag: "0.0.4"
  applicationPrefix: "/cardiology"
  applicationName: "Cardiology"
  signinUri: "https://$host/auth/cardiology/start?rd=$escaped_request_uri"
  authUri: "https://$host/auth/cardiology/auth"

reportWriter:
  enabled: true
  name: report-writer
  schedule: "0 0 * * *"
  nodeSelector: 
    role: usernp2
  image: 
    repository: acr7c02.azurecr.io/report-writer
    pullPolicy: IfNotPresent  
    tag: "0.0.1"
  keyVaultUrl: "https://vault7c02.vault.azure.net"
  secretName: "mongo-connection"
  databaseName: "PatientData"
  collectionName: "Default"

reportWriterServiceAccount:
  enabled: false
  name: neurologysvc
  clientId: "c1496868-d258-4cae-93b6-a3e00b70d60e"

persistentVolumeClaim:
  enabled: true
  name: store7c02a-container03-claim

persistentVolume:
  enabled: true
  name: store7c02a-container03
  azureResourceGroup: 2023-12-04-RG-01
  azureStorageAccount: store7c02a
  azureBlobContainer: container03